//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapShopProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResWebsite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResWebsite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LapShopProject.Resources.ResWebsite", typeof(ResWebsite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to us.
        /// </summary>
        public static string ChUs {
            get {
                return ResourceManager.GetString("ChUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string DollarSign {
            get {
                return ResourceManager.GetString("DollarSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string lblAddToCart {
            get {
                return ResourceManager.GetString("lblAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To WishList.
        /// </summary>
        public static string lblAddToWishList {
            get {
                return ResourceManager.GetString("lblAddToWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to home.
        /// </summary>
        public static string lblback_to_home {
            get {
                return ResourceManager.GetString("lblback to home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        public static string lblBuyNow {
            get {
                return ResourceManager.GetString("lblBuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check out.
        /// </summary>
        public static string lblCheckout {
            get {
                return ResourceManager.GetString("lblCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string lblCompare {
            get {
                return ResourceManager.GetString("lblCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue shopping.
        /// </summary>
        public static string lblContinueshopping {
            get {
                return ResourceManager.GetString("lblContinueshopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Products.
        /// </summary>
        public static string lblFeaturedProducts {
            get {
                return ResourceManager.GetString("lblFeaturedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string lblLarg {
            get {
                return ResourceManager.GetString("lblLarg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string lblLogut {
            get {
                return ResourceManager.GetString("lblLogut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string lblMideum {
            get {
                return ResourceManager.GetString("lblMideum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        public static string lblMy_Orders {
            get {
                return ResourceManager.GetString("lblMy Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Products.
        /// </summary>
        public static string lblNewProducts {
            get {
                return ResourceManager.GetString("lblNewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string lblOff {
            get {
                return ResourceManager.GetString("lblOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string lblProduct {
            get {
                return ResourceManager.GetString("lblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string lblQuantity {
            get {
                return ResourceManager.GetString("lblQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick View.
        /// </summary>
        public static string lblQuickView {
            get {
                return ResourceManager.GetString("lblQuickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string lblRating {
            get {
                return ResourceManager.GetString("lblRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOMMENDATIONS FOR YOU.
        /// </summary>
        public static string lblRECOMMENDATIONSFORYOU {
            get {
                return ResourceManager.GetString("lblRECOMMENDATIONSFORYOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save setting.
        /// </summary>
        public static string lblSave_setting {
            get {
                return ResourceManager.GetString("lblSave setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string lblShop {
            get {
                return ResourceManager.GetString("lblShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Now.
        /// </summary>
        public static string lblShopNow {
            get {
                return ResourceManager.GetString("lblShopNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size chart.
        /// </summary>
        public static string lblSizeChart {
            get {
                return ResourceManager.GetString("lblSizeChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string lblSmal {
            get {
                return ResourceManager.GetString("lblSmal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Your Review.
        /// </summary>
        public static string lblSubmitYourReview {
            get {
                return ResourceManager.GetString("lblSubmitYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support :.
        /// </summary>
        public static string lblSupport {
            get {
                return ResourceManager.GetString("lblSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL.
        /// </summary>
        public static string lblXLarg {
            get {
                return ResourceManager.GetString("lblXLarg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for a free account at our store. Registration is quick and easy. It allows you to be
        ///                        able to order from our shop. To start shopping click register..
        /// </summary>
        public static string PaFor_register_page {
            get {
                return ResourceManager.GetString("PaFor register page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free shipping world wide.
        /// </summary>
        public static string PaFreeShippingWorldWide {
            get {
                return ResourceManager.GetString("PaFreeShippingWorldWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New online special festival offer.
        /// </summary>
        public static string PaNewOnlineSpecialFestivalOffer {
            get {
                return ResourceManager.GetString("PaNewOnlineSpecialFestivalOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online service for new customer.
        /// </summary>
        public static string PaOnlineServiceForNewCustomer {
            get {
                return ResourceManager.GetString("PaOnlineServiceForNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is successfully processsed and your order is on the way.
        /// </summary>
        public static string POrderSuccess {
            get {
                return ResourceManager.GetString("POrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select size.
        /// </summary>
        public static string stSelectSize {
            get {
                return ResourceManager.GetString("stSelectSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 X 7 service.
        /// </summary>
        public static string Tit24X7service {
            get {
                return ResourceManager.GetString("Tit24X7service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Wishlist.
        /// </summary>
        public static string TitAdd_to_Wishlist {
            get {
                return ResourceManager.GetString("TitAdd to Wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TitAddress {
            get {
                return ResourceManager.GetString("TitAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string TitAddtoCart {
            get {
                return ResourceManager.GetString("TitAddtoCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us :.
        /// </summary>
        public static string TitCall_Us {
            get {
                return ResourceManager.GetString("TitCall Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string TitCart {
            get {
                return ResourceManager.GetString("TitCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string TitChat {
            get {
                return ResourceManager.GetString("TitChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out.
        /// </summary>
        public static string TitCheckout {
            get {
                return ResourceManager.GetString("TitCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string TitCompare {
            get {
                return ResourceManager.GetString("TitCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string Titcontact {
            get {
                return ResourceManager.GetString("Titcontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        public static string TitContact_No {
            get {
                return ResourceManager.GetString("TitContact No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        public static string TitCreate_an_Account {
            get {
                return ResourceManager.GetString("TitCreate an Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create account.
        /// </summary>
        public static string TitCreateAccount {
            get {
                return ResourceManager.GetString("TitCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer&apos;s login.
        /// </summary>
        public static string Titcustomer_s_login {
            get {
                return ResourceManager.GetString("Titcustomer\'s login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string TitDays {
            get {
                return ResourceManager.GetString("TitDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TitDescription {
            get {
                return ResourceManager.GetString("TitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TitDetails {
            get {
                return ResourceManager.GetString("TitDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TitEmail {
            get {
                return ResourceManager.GetString("TitEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected date of delivery.
        /// </summary>
        public static string Titexpected_date_of_delivery {
            get {
                return ResourceManager.GetString("Titexpected date of delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival offer.
        /// </summary>
        public static string TitFestivalOffer {
            get {
                return ResourceManager.GetString("TitFestivalOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string TitFilter {
            get {
                return ResourceManager.GetString("TitFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string TitFirstName {
            get {
                return ResourceManager.GetString("TitFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Shipping.
        /// </summary>
        public static string TitFreeShipping {
            get {
                return ResourceManager.GetString("TitFreeShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gpu.
        /// </summary>
        public static string TitGpu {
            get {
                return ResourceManager.GetString("TitGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Disk.
        /// </summary>
        public static string TitHardDisk {
            get {
                return ResourceManager.GetString("TitHardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrs.
        /// </summary>
        public static string TitHrs {
            get {
                return ResourceManager.GetString("TitHrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string TitImage {
            get {
                return ResourceManager.GetString("TitImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string TitLastName {
            get {
                return ResourceManager.GetString("TitLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Titlogin {
            get {
                return ResourceManager.GetString("Titlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string TitMin {
            get {
                return ResourceManager.GetString("TitMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string TitMyAccount {
            get {
                return ResourceManager.GetString("TitMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TitName {
            get {
                return ResourceManager.GetString("TitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer.
        /// </summary>
        public static string TitNew_Customer {
            get {
                return ResourceManager.GetString("TitNew Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string TitNewItem {
            get {
                return ResourceManager.GetString("TitNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string TitOrder_Date {
            get {
                return ResourceManager.GetString("TitOrder Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order ID.
        /// </summary>
        public static string Titorder_ID {
            get {
                return ResourceManager.GetString("Titorder ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Total.
        /// </summary>
        public static string TitOrder_Total {
            get {
                return ResourceManager.GetString("TitOrder Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string TitOs {
            get {
                return ResourceManager.GetString("TitOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Pages.
        /// </summary>
        public static string TitPages {
            get {
                return ResourceManager.GetString("TitPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string TitPass {
            get {
                return ResourceManager.GetString("TitPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment method.
        /// </summary>
        public static string Titpayment_method {
            get {
                return ResourceManager.GetString("Titpayment method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL DETAIL.
        /// </summary>
        public static string TitPERSONAL_DETAIL {
            get {
                return ResourceManager.GetString("TitPERSONAL DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string TitPhone {
            get {
                return ResourceManager.GetString("TitPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string TitPostal_Code {
            get {
                return ResourceManager.GetString("TitPostal Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string TitPrice {
            get {
                return ResourceManager.GetString("TitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proccessor.
        /// </summary>
        public static string TitProccessor {
            get {
                return ResourceManager.GetString("TitProccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        public static string TitProductDetails {
            get {
                return ResourceManager.GetString("TitProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product name.
        /// </summary>
        public static string TitProductname {
            get {
                return ResourceManager.GetString("TitProductname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string TitProducts {
            get {
                return ResourceManager.GetString("TitProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string TitProfile {
            get {
                return ResourceManager.GetString("TitProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity.
        /// </summary>
        public static string TitQty {
            get {
                return ResourceManager.GetString("TitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick View.
        /// </summary>
        public static string TitQuickView {
            get {
                return ResourceManager.GetString("TitQuickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ram Size.
        /// </summary>
        public static string TitRam {
            get {
                return ResourceManager.GetString("TitRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Products.
        /// </summary>
        public static string TitRelatedProducts {
            get {
                return ResourceManager.GetString("TitRelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Description.
        /// </summary>
        public static string TitReview_Des {
            get {
                return ResourceManager.GetString("TitReview Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Title.
        /// </summary>
        public static string TitReviewTitle {
            get {
                return ResourceManager.GetString("TitReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Reslution.
        /// </summary>
        public static string TitScreenReslution {
            get {
                return ResourceManager.GetString("TitScreenReslution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Size.
        /// </summary>
        public static string TitScreenSize {
            get {
                return ResourceManager.GetString("TitScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec.
        /// </summary>
        public static string TitSec {
            get {
                return ResourceManager.GetString("TitSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share It.
        /// </summary>
        public static string TitShareIt {
            get {
                return ResourceManager.GetString("TitShareIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shipping address.
        /// </summary>
        public static string Titshipping_address {
            get {
                return ResourceManager.GetString("Titshipping address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State / County.
        /// </summary>
        public static string TitState___County {
            get {
                return ResourceManager.GetString("TitState / County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Information.
        /// </summary>
        public static string TitStoreInfo {
            get {
                return ResourceManager.GetString("TitStoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string TitStreetName {
            get {
                return ResourceManager.GetString("TitStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subtotal.
        /// </summary>
        public static string Titsubtotal {
            get {
                return ResourceManager.GetString("Titsubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to summery.
        /// </summary>
        public static string Titsummery {
            get {
                return ResourceManager.GetString("Titsummery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Reminder.
        /// </summary>
        public static string TitTimeReminder {
            get {
                return ResourceManager.GetString("TitTimeReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        public static string TitTotal {
            get {
                return ResourceManager.GetString("TitTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price :.
        /// </summary>
        public static string TitTotalPrice {
            get {
                return ResourceManager.GetString("TitTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town/City.
        /// </summary>
        public static string TitTown_City {
            get {
                return ResourceManager.GetString("TitTown/City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        public static string TitTransaction_ID {
            get {
                return ResourceManager.GetString("TitTransaction ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string TitVideo {
            get {
                return ResourceManager.GetString("TitVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WishList.
        /// </summary>
        public static string TitWishList {
            get {
                return ResourceManager.GetString("TitWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Review.
        /// </summary>
        public static string TitWriteReview {
            get {
                return ResourceManager.GetString("TitWriteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Authorize.
        /// </summary>
        public static string TitYou_Are_Not_Authorize {
            get {
                return ResourceManager.GetString("TitYou Are Not Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your order details.
        /// </summary>
        public static string Tityour_order_details {
            get {
                return ResourceManager.GetString("Tityour order details", resourceCulture);
            }
        }
    }
}
